CREATE OR ALTER VIEW [dbo].[vwNConformidadeNotificacoes] AS
SELECT
	TACAO_CORRETIVA.RESPONSAVEL AS 'Responsável pela Ação',
	TACAO_CORRETIVA.COD_N_CONFORMIDADE AS 'Cód. Não Conf.',
	TN_CONFORMIDADE.TITULO AS 'Não Conformidade',
	TN_CONFORMIDADE.COD_OS_COMPLETO AS 'OS',
	TN_CONFORMIDADE.DESCRICAO_OS AS 'Descrição',
	TN_CONFORMIDADE.CLIENTE AS 'Cliente',
	TN_CONFORMIDADE.FAMILIA_N_CONFORME AS 'Família',
	TN_CONFORMIDADE.GRUPO_N_CONFORME AS 'Tipo',
	TN_CONFORMIDADE.DESTINO AS 'Destino',
	CONVERT(DATE, TN_CONFORMIDADE.DATA) AS 'Data de Abertura',
	TN_CONFORMIDADE.FASE AS 'Fase',
	TACAO_CORRETIVA.NOME AS 'Ação',
	CONVERT(DATE, TACAO_CORRETIVA.PRAZO_IMPLEMENTACAO) AS 'Prazo de Implementação',
	CASE
		WHEN GETDATE() > TACAO_CORRETIVA.PRAZO_IMPLEMENTACAO THEN DATEDIFF(DAY,TACAO_CORRETIVA.PRAZO_IMPLEMENTACAO,GETDATE()) 
		ELSE 0
	END AS 'Dias de Atraso'
FROM
	TACAO_CORRETIVA
INNER JOIN TN_CONFORMIDADE
	ON TACAO_CORRETIVA.COD_N_CONFORMIDADE = TN_CONFORMIDADE.CODIGO
WHERE
	TACAO_CORRETIVA.PRAZO_IMPLEMENTACAO IS NOT NULL AND
	(TN_CONFORMIDADE.DT_CONCLUSAO IS NULL OR
	TN_CONFORMIDADE.DT_EFETIVA_EFICACIA IS NULL) AND
	TACAO_CORRETIVA.COD_EMPRESA = 1 AND
	TACAO_CORRETIVA.DT_IMPLEMENTACAO IS NULL
GO


